import json
from pathlib import Path
from app.core.settings import settings
from app.modules.llm.service import LLMService
from app.modules.summary.prompt import SummaryPrompt
from app.modules.summary.exceptions import SummaryError

class SummaryGenerator:
    @staticmethod
    def generate_chunk_summaries(job_id: str) -> list:
        system = SummaryPrompt.get_chunk_system_prompt()
        user = SummaryPrompt.get_chunk_user_prompt()
        
        # This will create llm/merged/merged_response.json
        LLMService.process_job(job_id, system, user)
        
        merged_file = Path(settings.PROCESSED_DIR) / job_id / "llm" / "merged" / "merged_response.json"
        if not merged_file.exists():
            raise SummaryError(details={"reason": "merged_response.json not generated by LLM engine."})
            
        with open(merged_file, "r", encoding="utf-8") as f:
            data = json.load(f)
            
        return [r["content"] for r in data.get("responses", [])]
