import json
from pathlib import Path
from loguru import logger
from app.core.settings import settings
from app.modules.llm.service import LLMService
from app.modules.code_extraction.prompt import CodePrompt
from app.modules.code_extraction.exceptions import CodeExtractionError

class CodeGenerator:
    @staticmethod
    def extract_chunk_code(job_id: str) -> list:
        system = CodePrompt.get_chunk_system_prompt()
        user = CodePrompt.get_chunk_user_prompt()
        
        # Generates intermediate code into llm/merged/merged_response.json
        LLMService.process_job(job_id, system, user)
        
        merged_file = Path(settings.PROCESSED_DIR) / job_id / "llm" / "merged" / "merged_response.json"
        if not merged_file.exists():
            raise CodeExtractionError(details={"reason": "merged_response.json not generated by LLM engine."})
            
        with open(merged_file, "r", encoding="utf-8") as f:
            data = json.load(f)
            
        # Filter out NO_CODE_FOUND
        snippets = []
        for r in data.get("responses", []):
            content = r["content"].strip()
            if content and "NO_CODE_FOUND" not in content:
                snippets.append(content)
                
        return snippets
