import json
from pathlib import Path
from app.core.settings import settings
from app.modules.llm.service import LLMService
from app.modules.notes.prompt import NotesPrompt
from app.modules.notes.exceptions import NotesError

class NotesGenerator:
    @staticmethod
    def generate_chunk_notes(job_id: str) -> list:
        system = NotesPrompt.get_chunk_system_prompt()
        user = NotesPrompt.get_chunk_user_prompt()
        
        # Generates intermediate notes into llm/merged/merged_response.json
        LLMService.process_job(job_id, system, user)
        
        merged_file = Path(settings.PROCESSED_DIR) / job_id / "llm" / "merged" / "merged_response.json"
        if not merged_file.exists():
            raise NotesError(details={"reason": "merged_response.json not generated by LLM engine."})
            
        with open(merged_file, "r", encoding="utf-8") as f:
            data = json.load(f)
            
        return [r["content"] for r in data.get("responses", [])]
